### ISSUE TITLE
Could not pass event InventoryClickEvent to XClaim v1.10.5

### ISSUE THREAD

**Issue by PizzaRules668** [WasabiThumb/xclaim#61] opened 2023-11-20 22:35 UTC
I am running
- Paper: 1.20.2
- On Ubuntu Server 22.04

When you run the command `/xc` then click on the Enchantment Table (Version Info) the plugin throws this exceptions.

```
- [Mon 16:28:46 ERROR Minecraft] Could not pass event InventoryClickEvent to XClaim v1.10.5
java.lang.NoClassDefFoundError: Could not initialize class codes.wasabi.xclaim.gui.page.VersionInfoPage
    at xclaim-1.10.5.jar//codes.wasabi.xclaim.gui.page.MainPage.onClick(MainPage.java:166)
    at xclaim-1.10.5.jar//codes.wasabi.xclaim.gui.GUIHandler.onClick(GUIHandler.java:140)
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor176.execute(Unknown Source)
    at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
    at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
    at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
    at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3108)
    at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58)
    at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23)
    at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:53)
    at net.minecraft.server.TickTask.run(TickTask.java:18)
    at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153)
    at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
    at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1324)
    at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193)
    at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126)
    at net.minecraft.server.MinecraftServer.pollTaskInterna
```

**Comment by WasabiThumb** [comment] 2024-02-10 21:43
Duplicate of #66

**Closed by WasabiThumb** 2024-02-10 21:43 UTC
Labels: bug, paper
