### ISSUE TITLE
Chunk entry indicator broken on 1.21

### ISSUE THREAD

**Issue by Kittycraft0** [WasabiThumb/xclaim#103] opened 2024-07-29 21:47 UTC
When you walk into and out of a chunk in 1.20, you can see the chunk name and who's chunk it is. This indicator is gone entirely in 1.21. I want it back!!! please.

**Comment by WasabiThumb** [comment] 2024-07-29 23:22
Duplicate of #105

**Closed by WasabiThumb** 2024-07-29 23:22 UTC
