### ISSUE TITLE
Players can "cheat" UI items like Barrier blocks etc. with ingame "UI"

### ISSUE THREAD

**Issue by Mats4k** [WasabiThumb/xclaim#59] opened 2023-07-31 08:59 UTC
Hi,

i wanted to report an issue we found on our server regarding the use of the plugin.
If a players is in the "Claim Chunks" interface with the green and red dye, aswell as the barrier block, they can just rightclick an item frame to put the barrier block in there and then reconnect and keep the barrier block. 

See full reproduction steps in following clip:
https://github.com/WasabiThumb/xclaim/assets/50116190/acbc8fb0-1ec2-4b09-aebb-926d5a85ad0c

Cheers,
Mats

**Comment by Jerry2306** [comment] 2023-08-13 09:16
I can confirm the issue. The same happens on our Paper 1.20.1 server with plugin version 1.10.5

**Comment by WasabiThumb** [comment] 2023-10-17 18:58
Seems like there's a couple context leak issues. I have a definitive solution planned. Thanks for bringing this to my attention.

**Comment by WasabiThumb** [comment] 2024-02-10 21:44
Duplicate of #66

**Closed by WasabiThumb** 2024-02-10 21:44 UTC
Labels: bug
