### ISSUE TITLE
Can grab "Version Info" (Enchantment Table) on /xclaim menu

### ISSUE THREAD

**Issue by LittleKittyBoy** [WasabiThumb/xclaim#63] opened 2023-12-01 10:32 UTC
Too tired to go into detail, so just gonna give the video. Hope its enough.

_(I am only **op** so I do not have access to the console, so I am unsure if there is any console errors.)_

You can find the video here: https://streamable.com/wnnp8x
It expires in 2 days, if you haven't seen it and it's already expired let me know.

**Comment by WasabiThumb** [comment] 2023-12-02 16:54
> Too tired to go into detail, so just gonna give the video. Hope its enough.
> 
> _(I am only **op** so I do not have access to the console, so I am unsure if there is any console errors.)_
> 
> You can find the video here: https://streamable.com/wnnp8x It expires in 2 days, if you haven't seen it and it's already expired let me know.

Most likely an error in console with that as well, that would mean the GUI is failing catastrophically and reverting to vanilla behavior. Make sure to share that, just seeing the issue isn't enough to fix it since it's not intended behavior

**Comment by WasabiThumb** [comment] 2023-12-02 17:02
Possibly a duplicate of [#61](https://github.com/WasabiThumb/xclaim/issues/61) please confirm

**Comment by LittleKittyBoy** [comment] 2023-12-02 23:46
We are using Folia not paper. So not a duplicate?
I asked the owner to provide the error in the console if there is any. He will provide it when he is available to.

**Comment by WasabiThumb** [comment] 2023-12-03 00:08
> We are using Folia not paper. So not a duplicate? _(Idk, the owner knows more about Folia then i do.)_ I asked the owner to provide the error in the console if there is any. He will provide it when he is available to.

I did notice you are using folia, but folia is based on paper and typically issues with each come hand-in-hand unless they are likely to be affected by server regioning, based on the nature of the error I want to say it's probably PaperLib related so hence the tag.

In any case, confirming if this is a duplicate would just involve checking to see if the error you get is the same as the one in #61.

**Comment by LittleKittyBoy** [comment] 2023-12-03 00:17
Alr, just gotta wait for the server owner i guess

**Comment by WasabiThumb** [comment] 2024-02-10 21:43
Duplicate of #66

**Closed by WasabiThumb** 2024-02-10 21:43 UTC
Labels: duplicate, paper
