### ISSUE TITLE
BUG - [ISSUE with this plugin with another]

### ISSUE THREAD

**Issue by brandonbayliss8** [WasabiThumb/xclaim#60] opened 2023-10-15 11:51 UTC
Spigot Version : 1.20.2
GSit version : 1.50

[GSit] Loading GSit v1.5.0
[09:32:17] [Server thread/WARN]: [GSit] Loaded class io.papermc.paper.event.entity.EntityMoveEvent from XClaim v1.10.5 which is not a depend or softdepend of this plugin.
[09:32:17] [Server thread/ERROR]: net/kyori/adventure/text/Component initializing GSit v1.5.0 (Is it up to date?)
java.lang.NoClassDefFoundError: net/kyori/adventure/text/Component
    at dev.geco.gsit.GSitMain.onLoad(GSitMain.java:169) ~[?:?]
    at org.bukkit.craftbukkit.v1_20_R2.CraftServer.loadPlugins(CraftServer.java:442) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3916-Spigot-dba3cdc-2a38185]
    at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:219) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3916-Spigot-dba3cdc-2a38185]
    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:954) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3916-Spigot-dba3cdc-2a38185]
    at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:298) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3916-Spigot-dba3cdc-2a38185]
    at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.kyori.adventure.text.Component
    at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:160) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
    at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:112) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
    ... 6 more

And 

[09:32:48] [Server thread/INFO]: [GSit] Enabling GSit v1.5.0
[09:32:49] [Server thread/ERROR]: Error occurred while enabling GSit v1.5.0 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "dev.geco.gsit.manager.MManager.getMessage(String, Object[])" because the return value of "dev.geco.gsit.GSitMain.getMManager()" is null
    at dev.geco.gsit.GSitMain.setupCommands(GSitMain.java:209) ~[?:?]
    at dev.geco.gsit.GSitMain.onEnable(GSitMain.java:179) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
    at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:548) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3916-Spigot-dba3cdc-2a38185]
    at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:462) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3916-Spigot-dba3cdc-2a38185]
    at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:577) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3916-Spigot-dba3cdc-2a38185]
    at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:400) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3916-Spigot-dba3cdc-2a38185]
    at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:250) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3916-Spigot-dba3cdc-2a38185]
    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:954) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3916-Spigot-dba3cdc-2a38185]
    at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:298) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3916-Spigot-dba3cdc-2a38185]
    at java.lang.Thread.run(Thread.java:833) ~[?:?]

I have contacted the developer of GSIT and they have asked me to contact your self.

![image](https://github.com/WasabiThumb/xclaim/assets/16465713/7ebeaf6a-937b-478a-8fc4-30d62a4974d7)

**Comment by WasabiThumb** [comment] 2023-10-17 18:57
May be a duplicate of [this issue](https://github.com/Jannyboy11/InvSee-plus-plus/issues/75). Fixed on the main branch, will be included in the next release. It may be a while since I have other improvements planned, if you can't wait then clone the repo and build it yourself:
```sh
git clone https://github.com/WasabiThumb/xclaim.git
cd xclaim
mvn clean install
```
Output will be in ``target/xclaim-VERSION.jar``, assuming you have Java 8, Git and Maven installed.

**Comment by brandonbayliss8** [comment] 2023-10-17 19:42
From what I can see the master branch is the same as 1.10.5 and I already use that shown in the error log I gave.

**Comment by WasabiThumb** [comment] 2023-10-17 20:42
The version on master has not been bumped. It is different.

**Comment by WasabiThumb** [comment] 2024-02-13 18:12
Feel free to test again against 1.11.0 and re-open if the issue persists.

**Closed by WasabiThumb** 2024-02-13 18:12 UTC
Labels: duplicate, pending tests
