### ISSUE TITLE
BlueMap integration not highlighting all claims

### ISSUE THREAD

**Issue by Funkeemonkee06** [WasabiThumb/xclaim#112] opened 2024-08-09 11:49 UTC
Only one claim showing on the map at a time.

Happens when more than one claim exists in the world at a time.
Also unable to see chunks being claimed in real time unlike with first claim.

**Comment by WasabiThumb** [comment] 2024-08-09 12:00
Duplicate of #106

**Closed** 2024-08-09 12:00 UTC

**Comment by Funkeemonkee06** [comment] 2024-08-09 12:28
oops my bad
