### ISSUE TITLE
Cant Edit Permissions Ingame

### ISSUE THREAD

**Issue by MrTomatenblau** [WasabiThumb/xclaim#151] opened 2024-11-05 18:37 UTC
Hey, when i try to edit the Permissions Ingame nothing happens and the Console shows an Error. 
Im running Paper 1.21.1-131 i didnt touched files in layouts or lang folders. Here the Config [config.toml.txt](https://github.com/user-attachments/files/17637012/config.toml.txt)

Console Error:
`[19:30:13 ERROR]: Could not pass event InventoryClickEvent to XClaim v1.15.0
java.lang.AssertionError: Failed to load data for layout "permission-list"
        at xclaim-1.15.0.jar/codes.wasabi.xclaim.gui2.layout.GuiLayouts.get(GuiLayouts.java:91) ~[xclaim-1.15.0.jar:?]
        at xclaim-1.15.0.jar/codes.wasabi.xclaim.gui2.GuiInstance.setSpecInternal(GuiInstance.java:60) ~[xclaim-1.15.0.jar:?]
        at xclaim-1.15.0.jar/codes.wasabi.xclaim.gui2.GuiInstance.setSpec(GuiInstance.java:55) ~[xclaim-1.15.0.jar:?]
        at xclaim-1.15.0.jar/codes.wasabi.xclaim.gui2.GuiInstance.executeAction(GuiInstance.java:165) ~[xclaim-1.15.0.jar:?]
        at xclaim-1.15.0.jar/codes.wasabi.xclaim.gui2.GuiInstance.click(GuiInstance.java:183) ~[xclaim-1.15.0.jar:?]
        at xclaim-1.15.0.jar/codes.wasabi.xclaim.gui2.GuiManager.onClick(GuiManager.java:109) ~[xclaim-1.15.0.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor287.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-131-84281ce]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3224) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:69) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:33) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1535) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1512) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1505) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1464) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1471) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1316) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.io.IOException: Unexpected symbol: < @ char 24
        at xclaim-1.15.0.jar/codes.wasabi.xclaim.util.io.XmlReader.throwPositioned(XmlReader.java:271) ~[xclaim-1.15.0.jar:?]
        at xclaim-1.15.0.jar/codes.wasabi.xclaim.util.io.XmlReader.throwUnexpectedSymbol(XmlReader.java:266) ~[xclaim-1.15.0.jar:?]
        at xclaim-1.15.0.jar/codes.wasabi.xclaim.util.io.XmlReader.readSymbolInternal(XmlReader.java:106) ~[xclaim-1.15.0.jar:?]
        at xclaim-1.15.0.jar/codes.wasabi.xclaim.util.io.XmlReader.readSymbol(XmlReader.java:91) ~[xclaim-1.15.0.jar:?]
        at xclaim-1.15.0.jar/codes.wasabi.xclaim.util.io.XmlReader.readNode0(XmlReader.java:58) ~[xclaim-1.15.0.jar:?]
        at xclaim-1.15.0.jar/codes.wasabi.xclaim.util.io.XmlReader.readNode(XmlReader.java:49) ~[xclaim-1.15.0.jar:?]
        at xclaim-1.15.0.jar/codes.wasabi.xclaim.util.io.XmlReader.readNodeAssert(XmlReader.java:41) ~[xclaim-1.15.0.jar:?]
        at xclaim-1.15.0.jar/codes.wasabi.xclaim.util.io.XmlReader.readDocument(XmlReader.java:35) ~[xclaim-1.15.0.jar:?]
        at xclaim-1.15.0.jar/codes.wasabi.xclaim.gui2.layout.xml.XmlGuiLayout.read(XmlGuiLayout.java:44) ~[xclaim-1.15.0.jar:?]
        at xclaim-1.15.0.jar/codes.wasabi.xclaim.gui2.layout.xml.XmlGuiLayout.read(XmlGuiLayout.java:39) ~[xclaim-1.15.0.jar:?]
        at xclaim-1.15.0.jar/codes.wasabi.xclaim.gui2.layout.GuiLayouts$LoadWorker.resolveEntry(GuiLayouts.java:365) ~[xclaim-1.15.0.jar:?]
        at xclaim-1.15.0.jar/codes.wasabi.xclaim.gui2.layout.GuiLayouts$LoadWorker.run(GuiLayouts.java:298) ~[xclaim-1.15.0.jar:?]
        Suppressed: java.io.IOException: Unclosed tag: <layout> @ char 24
                at xclaim-1.15.0.jar/codes.wasabi.xclaim.util.io.XmlReader.throwPositioned(XmlReader.java:271) ~[xclaim-1.15.0.jar:?]
                at xclaim-1.15.0.jar/codes.wasabi.xclaim.util.io.XmlReader.close(XmlReader.java:252) ~[xclaim-1.15.0.jar:?]
                at xclaim-1.15.0.jar/codes.wasabi.xclaim.gui2.layout.xml.XmlGuiLayout.read(XmlGuiLayout.java:36) ~[xclaim-1.15.0.jar:?]
                at xclaim-1.15.0.jar/codes.wasabi.xclaim.gui2.layout.GuiLayouts$LoadWorker.resolveEntry(GuiLayouts.java:365) ~[xclaim-1.15.0.jar:?]
                at xclaim-1.15.0.jar/codes.wasabi.xclaim.gui2.layout.GuiLayouts$LoadWorker.run(GuiLayouts.java:298) ~[xclaim-1.15.0.jar:?]
`

**Comment by MrTomatenblau** [comment] 2024-11-05 18:41
When i switch to german language then nothing happens when i click on the shield (Edit Claim Permissons)

**Comment by WasabiThumb** [comment] 2024-11-05 18:42
Duplicate of #150 
What is the content of ``plugins/XClaim/layouts/permission-list.xml``?

**Comment by MrTomatenblau** [comment] 2024-11-05 20:52
[permission-list.xml.txt](https://github.com/user-attachments/files/17638408/permission-list.xml.txt)

**Comment by MrTomatenblau** [comment] 2024-11-05 21:02
@WasabiThumb I removed all comments  and now it seems to work fine as expected :)

**Comment by WasabiThumb** [comment] 2024-11-06 01:34
> @WasabiThumb I removed all comments and now it seems to work fine as expected :)

There are comments in other files; those don't cause issues?

**Comment by WasabiThumb** [comment] 2024-11-06 01:50
Ah, ok, I think I figured it out. ``permission-list.xml`` is the only file that has ``<`` inside of a comment. The parser doesn't handle this for some reason. My bad for assuming that updating a comment wouldn't break anything.

**Comment by WasabiThumb** [comment] 2024-11-06 02:11
Fixed in [1.15.1](https://github.com/WasabiThumb/xclaim/releases/tag/1.15.1).

**Closed by WasabiThumb** 2024-11-06 02:11 UTC
Labels: bug, pending tests
