### ISSUE TITLE
Not working after update.

### ISSUE THREAD

**Issue by Jamelos** [WasabiThumb/xclaim#150] opened 2024-11-04 19:40 UTC
So I'm using an  Aternos server, and everything worked well, but now, when I update, the bucket (general permission) which is the main option, does NOTHING. So I can't manage the permissions.

**Comment by Jamelos** [comment] 2024-11-04 20:17
It's getting even worse: I tried it again and now the bucket doesnt even appear...

**Comment by Jamelos** [comment] 2024-11-04 20:24
I re-downloaded it and changed it to GUI 1, but now can't disable permissions like Enter... is there a way to do both?

**Comment by WasabiThumb** [comment] 2024-11-04 20:41
Do you encounter a console error when trying to use the bucket with GUI v2?

**Comment by Jamelos** [comment] 2024-11-04 20:43
> Do you encounter a console error when trying to use the bucket with GUI v2?

Yes, and sometimes even the bucket does not open. As evidenced by another issue a week ago, I think the v2 gui is broken. The v1 works flawlessly, but doesn't have the upside of customization.

**Comment by WasabiThumb** [comment] 2024-11-04 20:50
> > Do you encounter a console error when trying to use the bucket with GUI v2?
> 
> Yes, and sometimes even the bucket does not appear. As evidenced by another issue a week ago, I think the v2 gui is broken. The v1 works flawlessly, but doesn't have the upside of customization.

v2 works fine for me, though I test on Linux and the issue you are likely referencing (#148) was produced on Windows. Seeing as how Aternos uses Linux servers, the exact error you are having is going to be very important. Please create a [paste](https://pastes.dev/). ^_^

**Comment by Jamelos** [comment] 2024-11-04 21:29
I tried it multiple times with and without Geyser. It even auto-detected the problem as Xclaim. This one has geyser:

https://mclo.gs/KuiLbtb

**Comment by WasabiThumb** [comment] 2024-11-05 02:43
> I tried it multiple times with and without Geyser. It even auto-detected the problem as Xclaim. This one has geyser:
> 
> https://mclo.gs/KuiLbtb

It's saying that your permission-list.xml is malformed because it is missing a closing ``</layout>`` tag. Can you share your ``plugins/XClaim/layouts/*.xml``? The layouts are properly formatted for a fresh install.

**Comment by WasabiThumb** [comment] 2024-11-05 18:31
See [this example](https://github.com/WasabiThumb/xclaim?tab=readme-ov-file#config-gui-layouts) for how to remove slots, and [this resource](https://www.w3schools.com/xml/xml_syntax.asp) for how the XML format works. The XML parser in this plugin actually doesn't support the prolog, but it's the same in every other way.

**Comment by Jamelos** [comment] 2024-11-05 19:41
Excuse me, I'm trying to remove the "Enter" and "Damage Friendly Entities", and I put this:
  <slot id="1"/>  
        <slot id="2"/>  
         
        <slot id="4"/>  
        <slot id="5"/>  
        <slot id="6"/>  
        <slot id="7"/>  
        <slot id="8"/>  
        <slot id="9"/>  

But the "enter" still appears, what am I doing wrong?

**Comment by Jamelos** [comment] 2024-11-05 19:56
I literally just reinstalled the plugin, did nothing, and yet the V2 didnt work. here is the code:

https://mclo.gs/KaNMwmL

**Comment by WasabiThumb** [comment] 2024-11-06 01:34
I see that now. Moving discussion to #151.

**Closed by WasabiThumb** 2024-11-06 01:34 UTC
Labels: invalid

**Comment by WasabiThumb** [comment] 2024-11-06 02:12
Fixed in [1.15.1](https://github.com/WasabiThumb/xclaim/releases/tag/1.15.1)

**Comment by WasabiThumb** [comment] 2024-11-06 19:30
I take it that your problem is gone, but I'm curious about this "bucket disappearing" thing. Are you able to reproduce this issue on 1.15.1?
