### ISSUE TITLE
Claiming chunk gets rid of Enchants on Armor 

### ISSUE THREAD

**Issue by Metrixstud** [WasabiThumb/xclaim#86] opened 2024-05-13 13:05 UTC
Title pretty self explanatory, when you claim a chunk anything in your inventory gets enchantments zoinked away.  Issue was discovered by a few of my players who exclaimed 'somebody stole the enchantments', then I did some investigating to find that this was the reason why.

**Comment by WasabiThumb** [comment] 2024-05-14 00:38
Is that custom enchantments or vanilla?

**Comment by Metrixstud** [comment] 2024-05-22 23:35
Vanilla

**Comment by WasabiThumb** [comment] 2024-07-14 18:14
I can't reproduce this issue for the life of me. A clip/detailed server info could help a lot.

**Comment by WasabiThumb** [comment] 2024-07-28 22:12
[Here](https://github.com/WasabiThumb/xclaim/blob/00823def93261519b8ca836a1a774a5a1f81ce65/src/main/java/codes/wasabi/xclaim/util/InventorySerializer.java#L55) and more specifically [here](https://github.com/WasabiThumb/xclaim/blob/00823def93261519b8ca836a1a774a5a1f81ce65/src/main/java/codes/wasabi/xclaim/platform/spigot/SpigotPlatform.java#L52) is the code that is responsible for storing data during claim mode. I've passed items through these methods multiple times on Paper 1.20 and have failed to find a case where enchant data is lost. If you would be interested in debugging this on your sever, let me know. Otherwise I'll have to close the issue, though it can be reopened with new information at any time.

**Comment by WasabiThumb** [comment] 2024-08-13 00:25
Closed due to inactivity

**Closed by WasabiThumb** 2024-08-13 00:25 UTC
Labels: bug, question
